export interface cartItem{
    Stock:number,
    category:string,
    createAt:string,
    description: string,
    image:any,
    name:string,
    numOfReviews:number,
    price:number,
    quantity:number,
    ratings:number,
    review:any,
    user:string,
    _v:number,
    _id:string,
}